#ifndef CONTROLEVENT_H
#define CONTROLEVENT_H

// Those are generated by:
// - Keyboard
// - LIRC
// - DBus
class ControlEvent
{
    public:
        ControlEvent();

        enum Type
        {
            EVENT_PAUSE_PLAY,   // or resume
            EVENT_STOP_PLAY,
            EVENT_10SEC_FORWARD,
            EVENT_10SEC_BACKWARD,
            EVENT_NEXT_IN_QUEUE,
            EVENT_PREV_IN_QUEUE,    // does restart if not within the first 5 seconds
            EVENT_CLEAR_QUEUE,
            EVENT_ENQUEUE_SONG,     // filename and singer
        };
};

#endif // CONTROLEVENT_H
